version: '3.9'
name: "nuxt-course"
services:
  postgres:
    container_name: nuxt-course
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_DB: 'nuxt-course'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'